version: '3.8'

services:

  backend:
    container_name: ds-backend
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  web:
    container_name: ds-web
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080

  redis-celery:
    image: redis:latest
    container_name: ds-redis_celery
    ports:
      - "6379:6379"

  celery:
    container_name: ds-celery
    build:
      context: ./services/backend/src/worker
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER=redis://redis-celery:6379/0
      - CELERY_BACKEND=redis://redis-celery:6379/1
      - CELERY_ACCEPT_CONTENT=pickle
      - CELERY_TASK_SERIALIZER=pickle
      - CELERY_RESULT_SERIALIZER=pickle
      - CELERY_RESULT_EXPIRES=60
    command: celery -A src.celery_app worker --loglevel=info
    volumes:
      - ./services/backend:/app
    depends_on:
      - redis-celery

